### ISSUE TITLE
Add an option to miss an ability

### ISSUE THREAD

**Issue by emcey** [genshinsim/gcsim#406] opened 2022-03-24 01:57 UTC
Purpose is to not use up elemental aura in certain situations.

**Comment by tzwang1** [comment] 2022-03-24 02:02
Looks like a duplicate of #195

**Comment by emcey** [comment] 2022-03-24 03:26
Sorry, I didn't see that one. Do you have any idea if this is something that will happen in the near future?

**Comment by tzwang1** [comment] 2022-03-24 04:31
No worries. I actually just started contributing this week, so not too sure what the status is for things. Maybe someone who has been working on the project longer would have a better idea.

**Comment by shizukayuki** [comment] 2022-03-24 06:40
Closing as duplicate of #195.

> Sorry, I didn't see that one. Do you have any idea if this is something that will happen in the near future?

not anytime soon afaik, will have to ask @srliao.

**Closed by shizukayuki** 2022-03-24 06:40 UTC
