### ISSUE TITLE
Adding a character to the simulator in the web UI removes parameter lines for all characters from the config

### ISSUE THREAD

**Issue by MrPillow1** [genshinsim/gcsim#1220] opened 2023-01-11 01:21 UTC
https://discord.com/channels/845087716541595668/869210750596554772/1062527070246285455

**Comment by k0l11** [comment] 2023-08-01 17:52
This also applies to weapon and set params. The problem is that the protos do not include the params at all, even though they are parsed and available to be added if the proto definitions were to be changed.

**Comment by k0l11** [comment] 2023-12-16 17:07
marking as wontfix because this UI was removed in v2.11.2

**Closed by k0l11** 2023-12-16 17:07 UTC
Labels: kind: wontfix, area: web
