### ISSUE TITLE
when using apl mode with flag +limit, the more iteration, the less yae dps

### ISSUE THREAD

**Issue by moriyasuwakoda** [genshinsim/gcsim#302] opened 2022-02-22 13:49 UTC
`yaemiko skill:3 +limit=1;`

## with +limit flag
iteration: 1, dps: 17071
iteration 10, dps: 3393
iteration: 100, dps: 359

## without +limit flag
iteration: 1, dps: 19328
iteration: 10, dps: 19114
iteration: 100: dps: 18936

---

```
####----GENERATED CHARACTER BLOCK DO NOT EDIT----####
yaemiko char lvl=90/90 cons=0 talent=6,8,6;
yaemiko add weapon="kagurasverity" refine=1 lvl=90/90;
yaemiko add stats def=625.0 hp=1.709e+4 atk=1645 er=1.000 em=345.0 cr=0.7360 cd=2.078 electro%=0.6160;

####----END GENERATED CHARACTER BLOCK DO NOT EDIT----####

options duration=14 iteration=1 mode=apl;
target lvl=90 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

active yaemiko;

yaemiko skill:3 +limit=1;
```

**Comment by HanSeoulOh** [comment] 2022-02-22 13:53
Thanks for finding this, looks like limit could be being set globally across instances instead of per simulation instance. @srliao

**Comment by Tsym-or-Tysm** [comment] 2022-02-22 14:04
Related to #233 - not sure if it's the same bug or not?

**Comment by srliao** [comment] 2022-02-23 03:32
i'll have to take a look but i believe it might be the same issue. i think has to do with the profile cloning code not properly cloning limit (too many pointers everywhere)

thanks for submitting this

**Comment by srliao** [comment] 2022-02-24 19:49
so i can't seem to reproduce this bug. if I run this config

```
options debug=true iteration=10000 duration=10 workers=60 mode=apl;

xingqiu char lvl=90/90 cons=6 talent=9,9,9; 
xingqiu add weapon="dullblade" refine=1 lvl=90/90;

##Default Enemy
target lvl=100 resist=0.1;

##Actions List
active xingqiu;

xingqiu attack +limit=2;
```

then if limit is working correctly xingqiu should only auto twice. this is the output


```
------------------------------------------
xingqiu contributed the following dps:
        Normal 0 (49.44% of total, 1.00 average damage procs): avg 20.01 [min: 19.52 | max: 29.28]
        Normal 1 (50.56% of total, 1.00 average damage procs): avg 20.47 [min: 19.95 | max: 29.93]
xingqiu total avg dps: 40.48; total percentage: 100%
------------------------------------------
Character ability usage:
xingqiu used the following abilities:
        attack: avg 2.00 [min: 2 | max: 2]
------------------------------------------
Character field time:
xingqiu on average active for 100% [min: 100% | max: 100%]
------------------------------------------
Element up time:
        Target #1
                none: avg 100.00% [min: 100.00% max: 100.00%]
        Target #2
                none: avg 100.00% [min: 100.00% max: 100.00%]
------------------------------------------
Damage by Target Omitted (Only 1 Target)
------------------------------------------
Average 404.78 damage over 10.00 seconds, resulting in 40 dps (min: 39.47 max: 59.21 std: 3.07)
Simulation completed 10000 iterations in 307.476285ms
```

so we see here that even in 10k iterations there's no variation at all in the number of autos used (exactly 2).

i'm in favour of closing this for now... not sure what's going on

**Comment by srliao** [comment] 2022-02-24 19:54
> 

Also I just tried running your config with 1, 10, 100 iterations and I'm not getting the same results. Not sure what's going on. Can you maybe share a viewer link where you have 100 iterations with 359 dps?

**Comment by srliao** [comment] 2022-02-24 19:55
@moriyasuwakoda Also I just tried running your config with 1, 10, 100 iterations and I'm not getting the same results. Not sure what's going on. Can you maybe share a viewer link where you have 100 iterations with 359 dps?

**Comment by moriyasuwakoda** [comment] 2022-02-26 13:00
@srliao Sorry for the delay
https://gcsim.app/viewer/share/S7XgIJ61_yT1W_IpWTDI-

**Comment by srliao** [comment] 2022-04-12 17:24
closing this for now as i can't see to reproduce the issue. i'm sure it'll pop up again at some point...

**Comment by moriyasuwakoda** [comment] 2022-04-15 04:34
@srliao 
it's 100% reproducible for me though.
here is the viewer link with config of xingqiu and it gives 0 dps under 10000 iteration
https://gcsim.app/viewer/share/-tY_mZBvq8Vdth__3L32T

```
------------------------------------------
xingqiu contributed the following dps:
	Normal 0 (49.45% of total, 0.00 average damage procs): avg 0.00 [min: 19.52 | max: 19.52] 
	Normal 1 (50.55% of total, 0.00 average damage procs): avg 0.00 [min: 19.95 | max: 19.95] 
xingqiu total avg dps: 0.01; total percentage: 100%
------------------------------------------
Character ability usage:
xingqiu used the following abilities:
	attack: avg 0.00 [min: 2 | max: 2]
------------------------------------------
Character field time:
xingqiu on average active for 100% [min: 100% | max: 100%]
------------------------------------------
Element up time:
	Target #1
		none: avg 100.00% [min: 100.00% max: 100.00%]
	Target #2
		none: avg 100.00% [min: 100.00% max: 100.00%]
------------------------------------------
Damage by Target Omitted (Only 1 Target)
------------------------------------------
Average 0.08 damage over 10.00 seconds, resulting in 0 dps (min: 0.00 max: 39.47 std: 0.56) 
Simulation completed 10000 iterations in 0s
```

also tried with different browsers(chrome/firefox) and both of them give 0 dps

**Comment by srliao** [comment] 2022-04-16 15:35
> @srliao it's 100% reproducible for me though. here is the viewer link with config of xingqiu and it gives 0 dps under 10000 iteration https://gcsim.app/viewer/share/-tY_mZBvq8Vdth__3L32T
> 
> ```
> ------------------------------------------
> xingqiu contributed the following dps:
> 	Normal 0 (49.45% of total, 0.00 average damage procs): avg 0.00 [min: 19.52 | max: 19.52] 
> 	Normal 1 (50.55% of total, 0.00 average damage procs): avg 0.00 [min: 19.95 | max: 19.95] 
> xingqiu total avg dps: 0.01; total percentage: 100%
> ------------------------------------------
> Character ability usage:
> xingqiu used the following abilities:
> 	attack: avg 0.00 [min: 2 | max: 2]
> ------------------------------------------
> Character field time:
> xingqiu on average active for 100% [min: 100% | max: 100%]
> ------------------------------------------
> Element up time:
> 	Target #1
> 		none: avg 100.00% [min: 100.00% max: 100.00%]
> 	Target #2
> 		none: avg 100.00% [min: 100.00% max: 100.00%]
> ------------------------------------------
> Damage by Target Omitted (Only 1 Target)
> ------------------------------------------
> Average 0.08 damage over 10.00 seconds, resulting in 0 dps (min: 0.00 max: 39.47 std: 0.56) 
> Simulation completed 10000 iterations in 0s
> ```
> 
> also tried with different browsers(chrome/firefox) and both of them give 0 dps

ok let me take a look at this again when i get the chance 🤔

**Closed** 2022-05-08 11:50 UTC
