### ISSUE TITLE
Fischl's Oz created from Burst is not snapshotting Bennett buff if it is gained during the Burst animation before she swaps out

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#253] opened 2022-02-12 19:15 UTC
From Veggie#0581 ([discord msg link](https://discord.com/channels/845087716541595668/869210750596554772/942133678383972392))

> Fischl swapping out after casting Q (in Oz-form) doesn't snapshot Bennett buff while it should:
> https://viewer.gcsim.app/share/1gsbs_MJSJRyyCampJlXW
> link to TCL:
> https://library.keqingmains.com/evidence/characters/electro/fischl#oz-summoned-from-ult-snapshots-fischls-stats-when-swapped-out

[fischl.gz](https://github.com/genshinsim/gcsim/files/8054326/fischl.gz)

at 4.57s and 25.05s, Fischl uses burst, gains bennett buff during the animation, but does not snapshot it on the resulting Oz, when she should snapshot the stats gained when she swaps out

**Comment by Tsym-or-Tysm** [comment] 2022-02-13 23:56
This is gated by #256 and so may not get fixed for a while.

Basically the problem is that in game, Fischl is locked into her burst animation for a full 2s, and the only way to cancel out of it is with a swap. The sim doesn't currently support that kind of action locking mechanism, and instead will always cancel Fischl out of her burst animation at the first available frame (21).

**Comment by srliao** [comment] 2022-07-24 16:03
need to test if this is fixed with updated fischl frames

**Comment by k0l11** [comment] 2022-08-12 13:30
part of #209. this is indeed fixed with updated fischl frames (had to add an attack before first fischl burst to catch bennett buff).
config:
```
options debug=true iteration=10000 duration=41 workers=24;

raidenshogun char lvl=90/90 cons=0 talent=9,9,9; 
raidenshogun add weapon="thecatch" refine=5 lvl=90/90;
raidenshogun add set="emblemofseveredfate" count=5;
raidenshogun add stats hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311 ; #main
raidenshogun add stats hp%=0.0992 hp=507.88 atk%=0.1984 atk=33.08 def%=0.124 def=39.36 em=39.64 cr=0.331 cd=0.7944 er=0.1102 ;

xiangling char lvl=90/90 cons=6 talent=9,9,9; 
xiangling add weapon="wavebreakersfin" refine=1 lvl=90/90;
xiangling add set="emblemofseveredfate" count=5;
xiangling add stats hp=4780 atk=311 er=0.518 pyro%=0.466 cr=0.311 ; #main
xiangling add stats hp%=0.0992 hp=507.88 atk%=0.1984 atk=33.08 def%=0.124 def=39.36 em=39.64 cr=0.331 cd=0.7944 er=0.1102 ;

fischl char lvl=90/90 cons=6 talent=9,9,9; 
fischl add weapon="alleyhunter" refine=1 lvl=90/90;
fischl add set="shimenawasreminiscence" count=2;
fischl add set="thunderingfury" count=2;
fischl add stats hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311; #main
fischl add stats hp%=0.0992 hp=507.88 atk%=0.1984 atk=33.08 def%=0.124 def=39.36 em=39.64 cr=0.331 cd=0.7944 er=0.1102 ;

bennett char lvl=90/90 cons=6 talent=9,9,9; 
bennett add weapon="thealleyflash" refine=1 lvl=90/90;
bennett add set="noblesseoblige" count=5;
bennett add stats hp=4780 atk=311 er=0.518 pyro%=0.466 cr=0.311 ; #main
bennett add stats hp%=0.0992 hp=507.88 atk%=0.0992 atk=33.08 def%=0.124 def=39.36 em=39.64 cr=0.331 cd=0.7944 er=0.2204 ;

##Default Enemy
target lvl=100 resist=.1;
target lvl=100 resist=.1;
energy every=10 amount=20;

##Actions List

active raiden;

raiden skill;
bennett burst,skill;
xiangling burst,skill;
fischl attack, burst;

raiden burst,attack:3,charge,attack:3,charge,attack:3,charge,charge,skill;

bennett skill;
fischl skill;

bennett attack:0;
wait(175);
bennett burst,skill;
xiangling burst,skill;
fischl burst;

raiden burst,attack:3,charge,attack:3,charge,attack:3,charge,charge,skill;

bennett skill;
xiangling attack:0;
wait(30);
```

**Closed** 2022-08-22 13:06 UTC
Labels: bug, blocked by other issue
